# 3 variables

In [1]:
import numpy as np
import scipy.linalg as sp_linalg

In [5]:
A= [[1,  4,  3],
    [3, -4,  7],
    [4, 9, -2]]
A= np.array(A)
b=[[4],
    [7],
    [2]]
b= np.array(b)

x=np.linalg.solve(A,b)
print("A=\n",A)
print("b=\n",b)
print("x=",x)

A=
 [[ 1  4  3]
 [ 3 -4  7]
 [ 4  9 -2]]
b=
 [[4]
 [7]
 [2]]
x= [[0.5]
 [0.2]
 [0.9]]


# check

In [6]:
Ai=np.linalg.inv(A)
b=np.linalg.solve(Ai,x)
b

array([[4.],
       [7.],
       [2.]])

# 5 variables

In [7]:
A= [[3,  4,  3,  2,  -4],
    [-2, -6,  4,  3,  2],
    [1, -8,  -1,  3,  -1],
    [5, 2,  3,  5, 1],
    [4, 1, -2,  3,  3]]
A= np.array(A)
b=[[4],
    [7],
    [5],
    [8],
    [2]]
b= np.array(b)

x=np.linalg.solve(A,b)
print("A=\n",A)
print("b=\n",b)
print("x=",x)

A=
 [[ 3  4  3  2 -4]
 [-2 -6  4  3  2]
 [ 1 -8 -1  3 -1]
 [ 5  2  3  5  1]
 [ 4  1 -2  3  3]]
b=
 [[4]
 [7]
 [5]
 [8]
 [2]]
x= [[ 0.60836177]
 [-0.44027304]
 [ 0.93088737]
 [ 0.60580205]
 [ 0.01706485]]


# check

In [8]:
Ai=np.linalg.inv(A)
b=np.linalg.solve(Ai,x)
b

array([[4.],
       [7.],
       [5.],
       [8.],
       [2.]])

# 10 variables

In [9]:
A= [[1,  4,  3,  2,  -4,  3,  4,  3,  8,  -4],
    [-2, -6,  4,  3,  2,  2,  0,  3,  6,  5],
    [1, -8,  -1,  3,  -1,  1,  4,  3,  1,  -7],
    [5, 2,  3,  5, 1,  1,  4,  3,  2,  8],
    [7, 3, -2,  4,  3,  0,  4,  16,  2,  -1],
    [9, 1, -2,  6,  7,  1,  2,  11,  2,  3],
    [5, 5, -2,  7,  2,  4,  3,  7,  2,  5],
    [8, 4, -12,  5,  8,  1,  4,  5,  2,  2],
    [6, 4, -2,  6,  3,  1,  4,  3,  5,  -4],
    [4, 1, -2,  5,  4,  2,  3,  0,  4,  14]]
A= np.array(A)
b=[[4],
    [11],
    [23],
    [87],
    [4],
    [2],
    [61],
    [7],
    [88],
    [13]]
b= np.array(b)

x=np.linalg.solve(A,b)
print("A=\n",A)
print("b=\n",b)
print("x=",x)

A=
 [[  1   4   3   2  -4   3   4   3   8  -4]
 [ -2  -6   4   3   2   2   0   3   6   5]
 [  1  -8  -1   3  -1   1   4   3   1  -7]
 [  5   2   3   5   1   1   4   3   2   8]
 [  7   3  -2   4   3   0   4  16   2  -1]
 [  9   1  -2   6   7   1   2  11   2   3]
 [  5   5  -2   7   2   4   3   7   2   5]
 [  8   4 -12   5   8   1   4   5   2   2]
 [  6   4  -2   6   3   1   4   3   5  -4]
 [  4   1  -2   5   4   2   3   0   4  14]]
b=
 [[ 4]
 [11]
 [23]
 [87]
 [ 4]
 [ 2]
 [61]
 [ 7]
 [88]
 [13]]
x= [[-26.74113597]
 [ 12.15806771]
 [ 18.67054697]
 [ 10.12508465]
 [ 32.44939834]
 [  4.58489912]
 [ 37.46315556]
 [ -4.17414068]
 [-17.527362  ]
 [ -6.19466167]]


# check

In [10]:
Ai=np.linalg.inv(A)
b=np.linalg.solve(Ai,x)
b

array([[ 4.],
       [11.],
       [23.],
       [87.],
       [ 4.],
       [ 2.],
       [61.],
       [ 7.],
       [88.],
       [13.]])